USE [BZP]
GO
INSERT u_Countries(CountryName) SELECT 'United States'
INSERT u_Countries(CountryName) SELECT 'Afghanistan'
INSERT u_Countries(CountryName) SELECT 'Akrotiri'
INSERT u_Countries(CountryName) SELECT 'Albania'
INSERT u_Countries(CountryName) SELECT 'Algeria'
INSERT u_Countries(CountryName) SELECT 'American Samoa'
INSERT u_Countries(CountryName) SELECT 'Andorra'
INSERT u_Countries(CountryName) SELECT 'Angola'
INSERT u_Countries(CountryName) SELECT 'Anguilla'
INSERT u_Countries(CountryName) SELECT 'Antarctica'
INSERT u_Countries(CountryName) SELECT 'Antigua and Barbuda'
INSERT u_Countries(CountryName) SELECT 'Argentina'
INSERT u_Countries(CountryName) SELECT 'Armenia'
INSERT u_Countries(CountryName) SELECT 'Aruba'
INSERT u_Countries(CountryName) SELECT 'Ashmore and Cartier Islands'
INSERT u_Countries(CountryName) SELECT 'Australia'
INSERT u_Countries(CountryName) SELECT 'Austria'
INSERT u_Countries(CountryName) SELECT 'Azerbaijan'
INSERT u_Countries(CountryName) SELECT 'Bahamas, The'
INSERT u_Countries(CountryName) SELECT 'Bahrain'
INSERT u_Countries(CountryName) SELECT 'Bangladesh'
INSERT u_Countries(CountryName) SELECT 'Barbados'
INSERT u_Countries(CountryName) SELECT 'Bassas da India'
INSERT u_Countries(CountryName) SELECT 'Belarus'
INSERT u_Countries(CountryName) SELECT 'Belgium'
INSERT u_Countries(CountryName) SELECT 'Belize'
INSERT u_Countries(CountryName) SELECT 'Benin'
INSERT u_Countries(CountryName) SELECT 'Bermuda'
INSERT u_Countries(CountryName) SELECT 'Bhutan'
INSERT u_Countries(CountryName) SELECT 'Bolivia'
INSERT u_Countries(CountryName) SELECT 'Bosnia and Herzegovina'
INSERT u_Countries(CountryName) SELECT 'Botswana'
INSERT u_Countries(CountryName) SELECT 'Bouvet Island'
INSERT u_Countries(CountryName) SELECT 'Brazil'
INSERT u_Countries(CountryName) SELECT 'British Indian Ocean Territory'
INSERT u_Countries(CountryName) SELECT 'British Virgin Islands'
INSERT u_Countries(CountryName) SELECT 'Brunei'
INSERT u_Countries(CountryName) SELECT 'Bulgaria'
INSERT u_Countries(CountryName) SELECT 'Burkina Faso'
INSERT u_Countries(CountryName) SELECT 'Burma'
INSERT u_Countries(CountryName) SELECT 'Burundi'
INSERT u_Countries(CountryName) SELECT 'Cambodia'
INSERT u_Countries(CountryName) SELECT 'Cameroon'
INSERT u_Countries(CountryName) SELECT 'Canada'
INSERT u_Countries(CountryName) SELECT 'Cape Verde'
INSERT u_Countries(CountryName) SELECT 'Cayman Islands'
INSERT u_Countries(CountryName) SELECT 'Central African Republic'
INSERT u_Countries(CountryName) SELECT 'Chad'
INSERT u_Countries(CountryName) SELECT 'Chile'
INSERT u_Countries(CountryName) SELECT 'China'
INSERT u_Countries(CountryName) SELECT 'Christmas Island'
INSERT u_Countries(CountryName) SELECT 'Clipperton Island'
INSERT u_Countries(CountryName) SELECT 'Cocos (Keeling) Islands'
INSERT u_Countries(CountryName) SELECT 'Colombia'
INSERT u_Countries(CountryName) SELECT 'Comoros'
INSERT u_Countries(CountryName) SELECT 'Congo, Democratic Republic of the'
INSERT u_Countries(CountryName) SELECT 'Congo, Republic of the'
INSERT u_Countries(CountryName) SELECT 'Cook Islands'
INSERT u_Countries(CountryName) SELECT 'Coral Sea Islands'
INSERT u_Countries(CountryName) SELECT 'Costa Rica'
INSERT u_Countries(CountryName) SELECT 'Cote d''Ivoire'
INSERT u_Countries(CountryName) SELECT 'Croatia'
INSERT u_Countries(CountryName) SELECT 'Cuba'
INSERT u_Countries(CountryName) SELECT 'Cyprus'
INSERT u_Countries(CountryName) SELECT 'Czech Republic'
INSERT u_Countries(CountryName) SELECT 'Denmark'
INSERT u_Countries(CountryName) SELECT 'Dhekelia'
INSERT u_Countries(CountryName) SELECT 'Djibouti'
INSERT u_Countries(CountryName) SELECT 'Dominica'
INSERT u_Countries(CountryName) SELECT 'Dominican Republic'
INSERT u_Countries(CountryName) SELECT 'Ecuador'
INSERT u_Countries(CountryName) SELECT 'Egypt'
INSERT u_Countries(CountryName) SELECT 'El Salvador'
INSERT u_Countries(CountryName) SELECT 'Equatorial Guinea'
INSERT u_Countries(CountryName) SELECT 'Eritrea'
INSERT u_Countries(CountryName) SELECT 'Estonia'
INSERT u_Countries(CountryName) SELECT 'Ethiopia'
INSERT u_Countries(CountryName) SELECT 'Europa Island'
INSERT u_Countries(CountryName) SELECT 'Falkland Islands (Islas Malvinas)'
INSERT u_Countries(CountryName) SELECT 'Faroe Islands'
INSERT u_Countries(CountryName) SELECT 'Fiji'
INSERT u_Countries(CountryName) SELECT 'Finland'
INSERT u_Countries(CountryName) SELECT 'France'
INSERT u_Countries(CountryName) SELECT 'French Guiana'
INSERT u_Countries(CountryName) SELECT 'French Polynesia'
INSERT u_Countries(CountryName) SELECT 'French Southern and Antarctic Lands'
INSERT u_Countries(CountryName) SELECT 'Gabon'
INSERT u_Countries(CountryName) SELECT 'Gambia, The'
INSERT u_Countries(CountryName) SELECT 'Gaza Strip'
INSERT u_Countries(CountryName) SELECT 'Georgia'
INSERT u_Countries(CountryName) SELECT 'Germany'
INSERT u_Countries(CountryName) SELECT 'Ghana'
INSERT u_Countries(CountryName) SELECT 'Gibraltar'
INSERT u_Countries(CountryName) SELECT 'Glorioso Islands'
INSERT u_Countries(CountryName) SELECT 'Greece'
INSERT u_Countries(CountryName) SELECT 'Greenland'
INSERT u_Countries(CountryName) SELECT 'Grenada'
INSERT u_Countries(CountryName) SELECT 'Guadeloupe'
INSERT u_Countries(CountryName) SELECT 'Guam'
INSERT u_Countries(CountryName) SELECT 'Guatemala'
INSERT u_Countries(CountryName) SELECT 'Guernsey'
INSERT u_Countries(CountryName) SELECT 'Guinea'
INSERT u_Countries(CountryName) SELECT 'Guinea-Bissau'
INSERT u_Countries(CountryName) SELECT 'Guyana'
INSERT u_Countries(CountryName) SELECT 'Haiti'
INSERT u_Countries(CountryName) SELECT 'Heard Island and McDonald Islands'
INSERT u_Countries(CountryName) SELECT 'Holy See (Vatican City)'
INSERT u_Countries(CountryName) SELECT 'Honduras'
INSERT u_Countries(CountryName) SELECT 'Hong Kong'
INSERT u_Countries(CountryName) SELECT 'Hungary'
INSERT u_Countries(CountryName) SELECT 'Iceland'
INSERT u_Countries(CountryName) SELECT 'India'
INSERT u_Countries(CountryName) SELECT 'Indonesia'
INSERT u_Countries(CountryName) SELECT 'Iran'
INSERT u_Countries(CountryName) SELECT 'Iraq'
INSERT u_Countries(CountryName) SELECT 'Ireland'
INSERT u_Countries(CountryName) SELECT 'Isle of Man'
INSERT u_Countries(CountryName) SELECT 'Israel'
INSERT u_Countries(CountryName) SELECT 'Italy'
INSERT u_Countries(CountryName) SELECT 'Jamaica'
INSERT u_Countries(CountryName) SELECT 'Jan Mayen'
INSERT u_Countries(CountryName) SELECT 'Japan'
INSERT u_Countries(CountryName) SELECT 'Jersey'
INSERT u_Countries(CountryName) SELECT 'Jordan'
INSERT u_Countries(CountryName) SELECT 'Juan de Nova Island'
INSERT u_Countries(CountryName) SELECT 'Kazakhstan'
INSERT u_Countries(CountryName) SELECT 'Kenya'
INSERT u_Countries(CountryName) SELECT 'Kiribati'
INSERT u_Countries(CountryName) SELECT 'Korea, North'
INSERT u_Countries(CountryName) SELECT 'Korea, South'
INSERT u_Countries(CountryName) SELECT 'Kuwait'
INSERT u_Countries(CountryName) SELECT 'Kyrgyzstan'
INSERT u_Countries(CountryName) SELECT 'Laos'
INSERT u_Countries(CountryName) SELECT 'Latvia'
INSERT u_Countries(CountryName) SELECT 'Lebanon'
INSERT u_Countries(CountryName) SELECT 'Lesotho'
INSERT u_Countries(CountryName) SELECT 'Liberia'
INSERT u_Countries(CountryName) SELECT 'Libya'
INSERT u_Countries(CountryName) SELECT 'Liechtenstein'
INSERT u_Countries(CountryName) SELECT 'Lithuania'
INSERT u_Countries(CountryName) SELECT 'Luxembourg'
INSERT u_Countries(CountryName) SELECT 'Macau'
INSERT u_Countries(CountryName) SELECT 'Macedonia'
INSERT u_Countries(CountryName) SELECT 'Madagascar'
INSERT u_Countries(CountryName) SELECT 'Malawi'
INSERT u_Countries(CountryName) SELECT 'Malaysia'
INSERT u_Countries(CountryName) SELECT 'Maldives'
INSERT u_Countries(CountryName) SELECT 'Mali'
INSERT u_Countries(CountryName) SELECT 'Malta'
INSERT u_Countries(CountryName) SELECT 'Marshall Islands'
INSERT u_Countries(CountryName) SELECT 'Martinique'
INSERT u_Countries(CountryName) SELECT 'Mauritania'
INSERT u_Countries(CountryName) SELECT 'Mauritius'
INSERT u_Countries(CountryName) SELECT 'Mayotte'
INSERT u_Countries(CountryName) SELECT 'Mexico'
INSERT u_Countries(CountryName) SELECT 'Micronesia, Federated States of'
INSERT u_Countries(CountryName) SELECT 'Moldova'
INSERT u_Countries(CountryName) SELECT 'Monaco'
INSERT u_Countries(CountryName) SELECT 'Mongolia'
INSERT u_Countries(CountryName) SELECT 'Montserrat'
INSERT u_Countries(CountryName) SELECT 'Morocco'
INSERT u_Countries(CountryName) SELECT 'Mozambique'
INSERT u_Countries(CountryName) SELECT 'Namibia'
INSERT u_Countries(CountryName) SELECT 'Nauru'
INSERT u_Countries(CountryName) SELECT 'Navassa Island'
INSERT u_Countries(CountryName) SELECT 'Nepal'
INSERT u_Countries(CountryName) SELECT 'Netherlands'
INSERT u_Countries(CountryName) SELECT 'Netherlands Antilles'
INSERT u_Countries(CountryName) SELECT 'New Caledonia'
INSERT u_Countries(CountryName) SELECT 'New Zealand'
INSERT u_Countries(CountryName) SELECT 'Nicaragua'
INSERT u_Countries(CountryName) SELECT 'Niger'
INSERT u_Countries(CountryName) SELECT 'Nigeria'
INSERT u_Countries(CountryName) SELECT 'Niue'
INSERT u_Countries(CountryName) SELECT 'Norfolk Island'
INSERT u_Countries(CountryName) SELECT 'Northern Mariana Islands'
INSERT u_Countries(CountryName) SELECT 'Norway'
INSERT u_Countries(CountryName) SELECT 'Oman'
INSERT u_Countries(CountryName) SELECT 'Pakistan'
INSERT u_Countries(CountryName) SELECT 'Palau'
INSERT u_Countries(CountryName) SELECT 'Panama'
INSERT u_Countries(CountryName) SELECT 'Papua New Guinea'
INSERT u_Countries(CountryName) SELECT 'Paracel Islands'
INSERT u_Countries(CountryName) SELECT 'Paraguay'
INSERT u_Countries(CountryName) SELECT 'Peru'
INSERT u_Countries(CountryName) SELECT 'Philippines'
INSERT u_Countries(CountryName) SELECT 'Pitcairn Islands'
INSERT u_Countries(CountryName) SELECT 'Poland'
INSERT u_Countries(CountryName) SELECT 'Portugal'
INSERT u_Countries(CountryName) SELECT 'Puerto Rico'
INSERT u_Countries(CountryName) SELECT 'Qatar'
INSERT u_Countries(CountryName) SELECT 'Reunion'
INSERT u_Countries(CountryName) SELECT 'Romania'
INSERT u_Countries(CountryName) SELECT 'Russia'
INSERT u_Countries(CountryName) SELECT 'Rwanda'
INSERT u_Countries(CountryName) SELECT 'Saint Helena'
INSERT u_Countries(CountryName) SELECT 'Saint Kitts and Nevis'
INSERT u_Countries(CountryName) SELECT 'Saint Lucia'
INSERT u_Countries(CountryName) SELECT 'Saint Pierre and Miquelon'
INSERT u_Countries(CountryName) SELECT 'Saint Vincent and the Grenadines'
INSERT u_Countries(CountryName) SELECT 'Samoa'
INSERT u_Countries(CountryName) SELECT 'San Marino'
INSERT u_Countries(CountryName) SELECT 'Sao Tome and Principe'
INSERT u_Countries(CountryName) SELECT 'Saudi Arabia'
INSERT u_Countries(CountryName) SELECT 'Senegal'
INSERT u_Countries(CountryName) SELECT 'Serbia and Montenegro'
INSERT u_Countries(CountryName) SELECT 'Seychelles'
INSERT u_Countries(CountryName) SELECT 'Sierra Leone'
INSERT u_Countries(CountryName) SELECT 'Singapore'
INSERT u_Countries(CountryName) SELECT 'Slovakia'
INSERT u_Countries(CountryName) SELECT 'Slovenia'
INSERT u_Countries(CountryName) SELECT 'Solomon Islands'
INSERT u_Countries(CountryName) SELECT 'Somalia'
INSERT u_Countries(CountryName) SELECT 'South Africa'
INSERT u_Countries(CountryName) SELECT 'South Georgia and the South Sandwich Islands'
INSERT u_Countries(CountryName) SELECT 'Spain'
INSERT u_Countries(CountryName) SELECT 'Spratly Islands'
INSERT u_Countries(CountryName) SELECT 'Sri Lanka'
INSERT u_Countries(CountryName) SELECT 'Sudan'
INSERT u_Countries(CountryName) SELECT 'Suriname'
INSERT u_Countries(CountryName) SELECT 'Svalbard'
INSERT u_Countries(CountryName) SELECT 'Swaziland'
INSERT u_Countries(CountryName) SELECT 'Sweden'
INSERT u_Countries(CountryName) SELECT 'Switzerland'
INSERT u_Countries(CountryName) SELECT 'Syria'
INSERT u_Countries(CountryName) SELECT 'Taiwan'
INSERT u_Countries(CountryName) SELECT 'Tajikistan'
INSERT u_Countries(CountryName) SELECT 'Tanzania'
INSERT u_Countries(CountryName) SELECT 'Thailand'
INSERT u_Countries(CountryName) SELECT 'Timor-Leste'
INSERT u_Countries(CountryName) SELECT 'Togo'
INSERT u_Countries(CountryName) SELECT 'Tokelau'
INSERT u_Countries(CountryName) SELECT 'Tonga'
INSERT u_Countries(CountryName) SELECT 'Trinidad and Tobago'
INSERT u_Countries(CountryName) SELECT 'Tromelin Island'
INSERT u_Countries(CountryName) SELECT 'Tunisia'
INSERT u_Countries(CountryName) SELECT 'Turkey'
INSERT u_Countries(CountryName) SELECT 'Turkmenistan'
INSERT u_Countries(CountryName) SELECT 'Turks and Caicos Islands'
INSERT u_Countries(CountryName) SELECT 'Tuvalu'
INSERT u_Countries(CountryName) SELECT 'Uganda'
INSERT u_Countries(CountryName) SELECT 'Ukraine'
INSERT u_Countries(CountryName) SELECT 'United Arab Emirates'
INSERT u_Countries(CountryName) SELECT 'United Kingdom'
INSERT u_Countries(CountryName) SELECT 'Uruguay'
INSERT u_Countries(CountryName) SELECT 'Uzbekistan'
INSERT u_Countries(CountryName) SELECT 'Vanuatu'
INSERT u_Countries(CountryName) SELECT 'Venezuela'
INSERT u_Countries(CountryName) SELECT 'Vietnam'
INSERT u_Countries(CountryName) SELECT 'Virgin Islands'
INSERT u_Countries(CountryName) SELECT 'Wake Island'
INSERT u_Countries(CountryName) SELECT 'Wallis and Futuna'
INSERT u_Countries(CountryName) SELECT 'West Bank'
INSERT u_Countries(CountryName) SELECT 'Western Sahara'
INSERT u_Countries(CountryName) SELECT 'Yemen'
INSERT u_Countries(CountryName) SELECT 'Zambia'
INSERT u_Countries(CountryName) SELECT 'Zimbabwe'
GO