USE [BZP]
GO
INSERT u_USStates(StateLN, StateSN) SELECT 'Alabama','AL'
INSERT u_USStates(StateLN, StateSN) SELECT 'Alaska','AK'
INSERT u_USStates(StateLN, StateSN) SELECT 'Arizona','AZ'
INSERT u_USStates(StateLN, StateSN) SELECT 'Arkansas','AR'
INSERT u_USStates(StateLN, StateSN) SELECT 'California','CA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Colorado','CO'
INSERT u_USStates(StateLN, StateSN) SELECT 'Connecticut','CT'
INSERT u_USStates(StateLN, StateSN) SELECT 'Delaware','DE'
INSERT u_USStates(StateLN, StateSN) SELECT 'Florida','FL'
INSERT u_USStates(StateLN, StateSN) SELECT 'Georgia','GA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Hawaii','HI'
INSERT u_USStates(StateLN, StateSN) SELECT 'Idaho','ID'
INSERT u_USStates(StateLN, StateSN) SELECT 'Illinois','IL'
INSERT u_USStates(StateLN, StateSN) SELECT 'Indiana','IN'
INSERT u_USStates(StateLN, StateSN) SELECT 'Iowa','IA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Kansas','KS'
INSERT u_USStates(StateLN, StateSN) SELECT 'Kentucky','KY'
INSERT u_USStates(StateLN, StateSN) SELECT 'Louisiana','LA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Maine','ME'
INSERT u_USStates(StateLN, StateSN) SELECT 'Maryland','MD'
INSERT u_USStates(StateLN, StateSN) SELECT 'Massachusetts','MA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Michigan','MI'
INSERT u_USStates(StateLN, StateSN) SELECT 'Minnesota','MN'
INSERT u_USStates(StateLN, StateSN) SELECT 'Mississippi','MS'
INSERT u_USStates(StateLN, StateSN) SELECT 'Missouri','MO'
INSERT u_USStates(StateLN, StateSN) SELECT 'Montana','MT'
INSERT u_USStates(StateLN, StateSN) SELECT 'Nebraska','NE'
INSERT u_USStates(StateLN, StateSN) SELECT 'Nevada','NV'
INSERT u_USStates(StateLN, StateSN) SELECT 'New Hampshire','NH'
INSERT u_USStates(StateLN, StateSN) SELECT 'New Jersey','NJ'
INSERT u_USStates(StateLN, StateSN) SELECT 'New Mexico','NM'
INSERT u_USStates(StateLN, StateSN) SELECT 'New York','NY'
INSERT u_USStates(StateLN, StateSN) SELECT 'North Carolina','NC'
INSERT u_USStates(StateLN, StateSN) SELECT 'North Dakota','ND'
INSERT u_USStates(StateLN, StateSN) SELECT 'Ohio','OH'
INSERT u_USStates(StateLN, StateSN) SELECT 'Oklahoma','OK'
INSERT u_USStates(StateLN, StateSN) SELECT 'Oregon','OR'
INSERT u_USStates(StateLN, StateSN) SELECT 'Pennsylvania','PA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Rhode Island','RI'
INSERT u_USStates(StateLN, StateSN) SELECT 'South Carolina','SC'
INSERT u_USStates(StateLN, StateSN) SELECT 'South Dakota','SD'
INSERT u_USStates(StateLN, StateSN) SELECT 'Tennessee','TN'
INSERT u_USStates(StateLN, StateSN) SELECT 'Texas','TX'
INSERT u_USStates(StateLN, StateSN) SELECT 'Utah','UT'
INSERT u_USStates(StateLN, StateSN) SELECT 'Vermont','VT'
INSERT u_USStates(StateLN, StateSN) SELECT 'Virginia','VA'
INSERT u_USStates(StateLN, StateSN) SELECT 'Washington','WA'
INSERT u_USStates(StateLN, StateSN) SELECT 'West Virginia','WV'
INSERT u_USStates(StateLN, StateSN) SELECT 'Wisconsin','WI'
INSERT u_USStates(StateLN, StateSN) SELECT 'Wyoming','WY'
INSERT u_USStates(StateLN, StateSN) SELECT 'American Samoa','AS'
INSERT u_USStates(StateLN, StateSN) SELECT 'District of Columbia','DC'
INSERT u_USStates(StateLN, StateSN) SELECT 'Federated States of Micronesia','FM'
INSERT u_USStates(StateLN, StateSN) SELECT 'Guam','GU'
INSERT u_USStates(StateLN, StateSN) SELECT 'North Marianas','MP'
INSERT u_USStates(StateLN, StateSN) SELECT 'Puerto Rico','PR'
INSERT u_USStates(StateLN, StateSN) SELECT 'Virgin Islands','VI'
INSERT u_USStates(StateLN, StateSN) SELECT 'Marshall Islands', 'MH'
INSERT u_USStates(StateLN, StateSN) SELECT 'Palau', 'PW'
 
GO